displayName=Station's Cozy Boats
author=StationEarthxo
description=Decorate your Sailing boat with animated, precisely positioned scenery that travels with the vessel
tags=sailing,boat,ships,objects,npc,animation,decorations,boatpack
plugins=com.cozyboats.WorldBuilderPlugin
